server.port=${PORT:8108}

spring.application.name=saberpro

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/saberpro}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Ciclismo7709}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Disable open session in view to avoid lazy loading issues
spring.jpa.open-in-view=false

# Server session config
server.servlet.session.timeout=60m
