TRUNCATE TABLE estudiantes RESTART IDENTITY CASCADE;
TRUNCATE TABLE coordinadores RESTART IDENTITY CASCADE;
TRUNCATE TABLE admins RESTART IDENTITY CASCADE;
TRUNCATE TABLE docentes RESTART IDENTITY CASCADE;
TRUNCATE TABLE directores RESTART IDENTITY CASCADE;
TRUNCATE TABLE facultades RESTART IDENTITY CASCADE;

INSERT INTO facultades (nombre, descripcion) VALUES ('Ingeniería de Sistemas', 'Facultad de Ingeniería de Sistemas y Computación');
INSERT INTO facultades (nombre, descripcion) VALUES ('Tecnología en Sistemas', 'Facultad de Tecnología en Sistemas e Informática');

INSERT INTO admins (nombre, correo, contrasena) VALUES ('Carlos García', 'admin@saberpro.edu.co', 'admin123');

INSERT INTO directores (nombre, correo, telefono, facultad_id, activo) VALUES ('Andrea Salazar', 'director@saberpro.edu.co', '3009876543', 1, true);

INSERT INTO docentes (tipo_documento, numero_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, correo, telefono, facultad_id, contrasena, activo) VALUES ('CC', '1000000003', 'Jorge', 'Luis', 'Méndez', 'Castro', 'docente@saberpro.edu.co', '3012345678', 1, 'admin123', true);

INSERT INTO coordinadores (tipo_documento, numero_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, correo, telefono, area_asignada, contrasena, activo) VALUES ('CC', '1000000002', 'María', 'Fernanda', 'López', 'Rodríguez', 'coordinador@saberpro.edu.co', '3001234567', 'Ingeniería de Sistemas', 'admin123', true);

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678901', 'CC', 'Juan', 'Sebastian', 'Barbosa', NULL, 'Juan Sebastian Barbosa', 'juan.barbosa@estudiante.universidad.edu.co', '3157000001', 'EK20183007722', 10, 'Ingeniería de Sistemas', 'Profesional', 200.0, 'Nivel 4', 128.0, 'Nivel 2', 182.0, 'Nivel 3', 202.0, 'Nivel 4', 206.0, 'Nivel 4', 183.0, 'B1', 185.0, 'Nivel 3', 160.0, 'Nivel 3', 197.0, 'Nivel 4', true, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678902', 'CC', 'Laura', NULL, 'Quintero', NULL, 'Laura Quintero', 'laura.quintero@estudiante.universidad.edu.co', '3157000002', 'EK20183140703', 10, 'Ingeniería de Sistemas', 'Profesional', 165.0, 'Nivel 3', 125.0, 'Nivel 1', 151.0, 'Nivel 2', 179.0, 'Nivel 3', 163.0, 'Nivel 3', 205.0, 'B2', 182.0, 'Nivel 3', 144.0, 'Nivel 2', 136.0, 'Nivel 2', true, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678903', 'CC', 'Carlos', 'Andres', 'Parra', NULL, 'Carlos Andres Parra', 'carlos.parra@estudiante.universidad.edu.co', '3157000003', 'EK20183040545', 10, 'Ingeniería de Sistemas', 'Profesional', 164.0, 'Nivel 3', 159.0, 'Nivel 3', 172.0, 'Nivel 3', 182.0, 'Nivel 3', 142.0, 'Nivel 2', 165.0, 'A2', 167.0, 'Nivel 3', 132.0, 'Nivel 2', 148.0, 'Nivel 2', true, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678904', 'CC', 'Maria', NULL, 'Anaya', NULL, 'Maria Anaya', 'maria.anaya@estudiante.universidad.edu.co', '3157000004', 'EK20183025381', 10, 'Ingeniería de Sistemas', 'Profesional', 160.0, 'Nivel 3', 146.0, 'Nivel 2', 199.0, 'Nivel 4', 157.0, 'Nivel 3', 149.0, 'Nivel 2', 147.0, 'A2', 174.0, 'Nivel 3', 127.0, 'Nivel 2', 171.0, 'Nivel 3', true, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678905', 'CC', 'Daniel', 'Felipe', 'Flor', NULL, 'Daniel Felipe Flor', 'daniel.flor@estudiante.universidad.edu.co', '3157000005', 'EK20183025335', 10, 'Ingeniería de Sistemas', 'Profesional', 160.0, 'Nivel 3', 198.0, 'Nivel 4', 153.0, 'Nivel 2', 147.0, 'Nivel 2', 157.0, 'Nivel 3', 146.0, 'A2', 168.0, 'Nivel 3', 114.0, 'Nivel 1', 160.0, 'Nivel 3', true, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678906', 'CC', 'Sofia', 'Valentina', 'Garcia', NULL, 'Sofia Valentina Garcia', 'sofia.garcia@estudiante.universidad.edu.co', '3157000006', 'EK20183122648', 10, 'Ingeniería de Sistemas', 'Profesional', 157.0, 'Nivel 3', 179.0, 'Nivel 3', 172.0, 'Nivel 3', 158.0, 'Nivel 3', 140.0, 'Nivel 2', 136.0, 'A1', 128.0, 'Nivel 2', 121.0, 'Nivel 1', 142.0, 'Nivel 2', true, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678907', 'CC', 'Jose', 'David', 'Manosalva', NULL, 'Jose David Manosalva', 'jose.manosalva@estudiante.universidad.edu.co', '3157000007', 'EK20183064605', 10, 'Ingeniería de Sistemas', 'Profesional', 153.0, 'Nivel 2', 115.0, 'Nivel 1', 152.0, 'Nivel 2', 159.0, 'Nivel 3', 172.0, 'Nivel 3', 165.0, 'A2', 142.0, 'Nivel 2', 118.0, 'Nivel 1', 119.0, 'Nivel 1', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678908', 'CC', 'Ana', 'Maria', 'Mendoza', NULL, 'Ana Maria Mendoza', 'ana.mendoza@estudiante.universidad.edu.co', '3157000008', 'EK20183187351', 10, 'Ingeniería de Sistemas', 'Profesional', 151.0, 'Nivel 2', 132.0, 'Nivel 2', 123.0, 'Nivel 1', 125.0, 'Nivel 1', 169.0, 'Nivel 3', 204.0, 'B2', 173.0, 'Nivel 3', 127.0, 'Nivel 2', 171.0, 'Nivel 3', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678909', 'CC', 'Santiago', NULL, 'Beltran', NULL, 'Santiago Beltran', 'santiago.beltran@estudiante.universidad.edu.co', '3157000009', 'EK20183233820', 10, 'Ingeniería de Sistemas', 'Profesional', 150.0, 'Nivel 2', 86.0, 'Nivel 1', 187.0, 'Nivel 3', 160.0, 'Nivel 3', 171.0, 'Nivel 3', 148.0, 'A2', 162.0, 'Nivel 3', 125.0, 'Nivel 1', 142.0, 'Nivel 2', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678910', 'CC', 'Valentina', NULL, 'Santamaria', NULL, 'Valentina Santamaria', 'valentina.santamaria@estudiante.universidad.edu.co', '3157000010', 'EK20183030016', 10, 'Ingeniería de Sistemas', 'Profesional', 150.0, 'Nivel 2', 175.0, 'Nivel 3', 149.0, 'Nivel 2', 145.0, 'Nivel 2', 158.0, 'Nivel 3', 125.0, 'A1', 162.0, 'Nivel 3', 76.0, 'Nivel 1', 125.0, 'Nivel 1', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678911', 'CC', 'Andres', NULL, 'Sanchez', NULL, 'Andres Sanchez', 'andres.sanchez@estudiante.universidad.edu.co', '3157000011', 'EK20183047073', 10, 'Ingeniería de Sistemas', 'Profesional', 149.0, 'Nivel 2', 209.0, 'Nivel 4', 143.0, 'Nivel 2', 117.0, 'Nivel 1', 129.0, 'Nivel 2', 147.0, 'A2', 137.0, 'Nivel 2', 125.0, 'Nivel 1', 136.0, 'Nivel 2', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678912', 'CC', 'Paola', NULL, 'Romero', NULL, 'Paola Romero', 'paola.romero@estudiante.universidad.edu.co', '3157000012', 'EK20183236451', 10, 'Ingeniería de Sistemas', 'Profesional', 146.0, 'Nivel 2', 93.0, 'Nivel 1', 183.0, 'Nivel 3', 155.0, 'Nivel 2', 164.0, 'Nivel 3', 133.0, 'A1', 174.0, 'Nivel 3', 130.0, 'Nivel 2', 154.0, 'Nivel 2', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678913', 'CC', 'Natalia', NULL, 'Luna', NULL, 'Natalia Luna', 'natalia.luna@estudiante.universidad.edu.co', '3157000013', 'EK20183041714', 10, 'Ingeniería de Sistemas', 'Profesional', 141.0, 'Nivel 2', 125.0, 'Nivel 1', 157.0, 'Nivel 3', 138.0, 'Nivel 2', 135.0, 'Nivel 2', 152.0, 'A2', 176.0, 'Nivel 3', 128.0, 'Nivel 2', 165.0, 'Nivel 3', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678914', 'CC', 'Diego', NULL, 'Triana', NULL, 'Diego Triana', 'diego.triana@estudiante.universidad.edu.co', '3157000014', 'EK20183187801', 10, 'Ingeniería de Sistemas', 'Profesional', 141.0, 'Nivel 2', 150.0, 'Nivel 2', 136.0, 'Nivel 2', 145.0, 'Nivel 2', 150.0, 'Nivel 2', 126.0, 'A1', 148.0, 'Nivel 2', 129.0, 'Nivel 2', 131.0, 'Nivel 2', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678915', 'CC', 'Camila', NULL, 'Suarez', NULL, 'Camila Suarez', 'camila.suarez@estudiante.universidad.edu.co', '3157000015', 'EK20183176566', 10, 'Ingeniería de Sistemas', 'Profesional', 140.0, 'Nivel 2', 128.0, 'Nivel 2', 146.0, 'Nivel 2', 146.0, 'Nivel 2', 132.0, 'Nivel 2', 147.0, 'A2', 130.0, 'Nivel 2', 110.0, 'Nivel 1', 125.0, 'Nivel 1', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678916', 'CC', 'Miguel', NULL, 'Garcia', NULL, 'Miguel Garcia', 'miguel.garcia@estudiante.universidad.edu.co', '3157000016', 'EK20183204427', 10, 'Ingeniería de Sistemas', 'Profesional', 139.0, 'Nivel 2', 129.0, 'Nivel 2', 138.0, 'Nivel 2', 148.0, 'Nivel 2', 146.0, 'Nivel 2', 135.0, 'A1', 109.0, 'Nivel 1', 107.0, 'Nivel 1', 131.0, 'Nivel 2', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678917', 'CC', 'Luisa', NULL, 'Pinzon', NULL, 'Luisa Pinzon', 'luisa.pinzon@estudiante.universidad.edu.co', '3157000017', 'EK20183196280', 10, 'Ingeniería de Sistemas', 'Profesional', 138.0, 'Nivel 2', 153.0, 'Nivel 2', 123.0, 'Nivel 1', 127.0, 'Nivel 1', 147.0, 'Nivel 2', 140.0, 'A1', 145.0, 'Nivel 2', 143.0, 'Nivel 2', 160.0, 'Nivel 3', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678918', 'CC', 'Sergio', NULL, 'Jaimes', NULL, 'Sergio Jaimes', 'sergio.jaimes@estudiante.universidad.edu.co', '3157000018', 'EK20183173799', 10, 'Ingeniería de Sistemas', 'Profesional', 137.0, 'Nivel 2', 166.0, 'Nivel 3', 157.0, 'Nivel 3', 124.0, 'Nivel 1', 100.0, 'Nivel 1', 140.0, 'A1', 100.0, 'Nivel 1', 105.0, 'Nivel 1', 113.0, 'Nivel 1', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678919', 'CC', 'Karen', NULL, 'Niño', NULL, 'Karen Niño', 'karen.nino@estudiante.universidad.edu.co', '3157000019', 'EK20183009565', 10, 'Ingeniería de Sistemas', 'Profesional', 134.0, 'Nivel 2', 165.0, 'Nivel 3', 137.0, 'Nivel 2', 136.0, 'Nivel 2', 118.0, 'Nivel 1', 116.0, 'A0', 146.0, 'Nivel 2', 122.0, 'Nivel 1', 154.0, 'Nivel 2', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678920', 'CC', 'Jhon', NULL, 'Fabian', NULL, 'Jhon Fabian', 'jhon.fabian@estudiante.universidad.edu.co', '3157000020', 'EK20183117756', 10, 'Ingeniería de Sistemas', 'Profesional', 133.0, 'Nivel 2', 139.0, 'Nivel 2', 93.0, 'Nivel 1', 168.0, 'Nivel 3', 150.0, 'Nivel 2', 114.0, 'A0', 102.0, 'Nivel 1', 123.0, 'Nivel 1', 94.0, 'Nivel 1', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678921', 'CC', 'Paula', NULL, 'Hernandez', NULL, 'Paula Hernandez', 'paula.hernandez@estudiante.universidad.edu.co', '3157000021', 'EK20183044579', 10, 'Ingeniería de Sistemas', 'Profesional', 132.0, 'Nivel 2', 116.0, 'Nivel 1', 166.0, 'Nivel 3', 136.0, 'Nivel 2', 104.0, 'Nivel 1', 140.0, 'A1', 158.0, 'Nivel 3', 125.0, 'Nivel 1', 154.0, 'Nivel 2', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678922', 'CC', 'Nicolas', NULL, 'Larios', NULL, 'Nicolas Larios', 'nicolas.larios@estudiante.universidad.edu.co', '3157000022', 'EK20183045760', 10, 'Ingeniería de Sistemas', 'Profesional', 131.0, 'Nivel 2', 149.0, 'Nivel 2', 123.0, 'Nivel 1', 129.0, 'Nivel 1', 121.0, 'Nivel 1', 131.0, 'A1', 101.0, 'Nivel 1', 102.0, 'Nivel 1', 165.0, 'Nivel 3', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678923', 'CC', 'Andrea', NULL, 'Calderon', NULL, 'Andrea Calderon', 'andrea.calderon@estudiante.universidad.edu.co', '3157000023', 'EK20183034044', 10, 'Ingeniería de Sistemas', 'Profesional', 130.0, 'Nivel 2', 127.0, 'Nivel 2', 147.0, 'Nivel 2', 134.0, 'Nivel 2', 111.0, 'Nivel 1', 131.0, 'A1', 65.0, 'Nivel 1', 112.0, 'Nivel 1', 94.0, 'Nivel 1', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678924', 'CC', 'Mario', NULL, 'Villarreal', NULL, 'Mario Villarreal', 'mario.villarreal@estudiante.universidad.edu.co', '3157000024', 'EK20183041521', 10, 'Ingeniería de Sistemas', 'Profesional', 129.0, 'Nivel 2', 96.0, 'Nivel 1', 162.0, 'Nivel 3', 114.0, 'Nivel 1', 131.0, 'Nivel 2', 144.0, 'A1', 122.0, 'Nivel 1', 112.0, 'Nivel 1', 131.0, 'Nivel 2', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678925', 'CC', 'Juliana', NULL, 'Restrepo', NULL, 'Juliana Restrepo', 'juliana.restrepo@estudiante.universidad.edu.co', '3157000025', 'EK20183027436', 10, 'Ingeniería de Sistemas', 'Profesional', 126.0, 'Nivel 2', 81.0, 'Nivel 1', 134.0, 'Nivel 2', 126.0, 'Nivel 2', 149.0, 'Nivel 2', 139.0, 'A1', 127.0, 'Nivel 2', 136.0, 'Nivel 2', 142.0, 'Nivel 2', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678926', 'CC', 'Esteban', NULL, 'Caceres', NULL, 'Esteban Caceres', 'esteban.caceres@estudiante.universidad.edu.co', '3157000026', 'EK20183031592', 10, 'Ingeniería de Sistemas', 'Profesional', 125.0, 'Nivel 1', 124.0, 'Nivel 1', 135.0, 'Nivel 2', 108.0, 'Nivel 1', 92.0, 'Nivel 1', 165.0, 'A2', 132.0, 'Nivel 2', 104.0, 'Nivel 1', 131.0, 'Nivel 2', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678927', 'CC', 'Adriana', NULL, 'Tabares', NULL, 'Adriana Tabares', 'adriana.tabares@estudiante.universidad.edu.co', '3157000027', 'EK20183004153', 10, 'Ingeniería de Sistemas', 'Profesional', 124.0, 'Nivel 1', 131.0, 'Nivel 2', 131.0, 'Nivel 2', 107.0, 'Nivel 1', 88.0, 'Nivel 1', 162.0, 'A2', 136.0, 'Nivel 2', 112.0, 'Nivel 1', 148.0, 'Nivel 2', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678928', 'CC', 'Felipe', NULL, 'Naranjo', NULL, 'Felipe Naranjo', 'felipe.naranjo@estudiante.universidad.edu.co', '3157000028', 'EK20183030783', 10, 'Ingeniería de Sistemas', 'Profesional', 122.0, 'Nivel 1', 166.0, 'Nivel 3', 113.0, 'Nivel 1', 113.0, 'Nivel 1', 112.0, 'Nivel 1', 106.0, 'A0', 135.0, 'Nivel 2', 117.0, 'Nivel 1', 119.0, 'Nivel 1', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678929', 'CC', 'Monica', NULL, 'Prada', NULL, 'Monica Prada', 'monica.prada@estudiante.universidad.edu.co', '3157000029', 'EK20183024754', 10, 'Ingeniería de Sistemas', 'Profesional', 122.0, 'Nivel 1', 119.0, 'Nivel 1', 125.0, 'Nivel 1', 137.0, 'Nivel 2', 107.0, 'Nivel 1', 123.0, 'A1', 83.0, 'Nivel 1', 104.0, 'Nivel 1', 119.0, 'Nivel 1', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678930', 'CC', 'Roberto', NULL, 'Vargas', NULL, 'Roberto Vargas', 'roberto.vargas@estudiante.universidad.edu.co', '3157000030', 'EK20183186200', 10, 'Ingeniería de Sistemas', 'Profesional', 114.0, 'Nivel 1', 95.0, 'Nivel 1', 120.0, 'Nivel 1', 151.0, 'Nivel 2', 86.0, 'Nivel 1', 119.0, 'A0', 149.0, 'Nivel 2', 103.0, 'Nivel 1', 119.0, 'Nivel 1', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678931', 'CC', 'Claudia', NULL, 'Torres', NULL, 'Claudia Torres', 'claudia.torres@estudiante.universidad.edu.co', '3157000031', 'EK20183182410', 10, 'Ingeniería de Sistemas', 'Profesional', 113.0, 'Nivel 1', 109.0, 'Nivel 1', 105.0, 'Nivel 1', 104.0, 'Nivel 1', 103.0, 'Nivel 1', 142.0, 'A1', 102.0, 'Nivel 1', 135.0, 'Nivel 2', 80.0, 'Nivel 1', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678932', 'CC', 'Hector', NULL, 'Ortiz', NULL, 'Hector Ortiz', 'hector.ortiz@estudiante.universidad.edu.co', '3157000032', 'EK20183213735', 10, 'Ingeniería de Sistemas', 'Profesional', 107.0, 'Nivel 1', 128.0, 'Nivel 2', 81.0, 'Nivel 1', 107.0, 'Nivel 1', 102.0, 'Nivel 1', 119.0, 'A0', 130.0, 'Nivel 2', 111.0, 'Nivel 1', 125.0, 'Nivel 1', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678933', 'CC', 'Lina', NULL, 'Villamizar', NULL, 'Lina Villamizar', 'lina.villamizar@estudiante.universidad.edu.co', '3157000033', 'EK20183065220', 10, 'Ingeniería de Sistemas', 'Profesional', 106.0, 'Nivel 1', 134.0, 'Nivel 2', 96.0, 'Nivel 1', 92.0, 'Nivel 1', 110.0, 'Nivel 1', 97.0, 'A0', 83.0, 'Nivel 1', 107.0, 'Nivel 1', 119.0, 'Nivel 1', false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678934', 'CC', 'Alexis', NULL, 'Higuera', NULL, 'Alexis Higuera', 'alexis.higuera@estudiante.universidad.edu.co', '3157000034', 'EK20183207870', 10, 'Ingeniería de Sistemas', 'Profesional', NULL, 'ANULADO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678935', 'CC', 'Fernando', NULL, 'Matiz', NULL, 'Fernando Matiz', 'fernando.matiz@estudiante.universidad.edu.co', '3157000035', 'EK20183144329', 10, 'Ingeniería de Sistemas', 'Profesional', NULL, 'ANULADO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, true, '2026-05-15');

INSERT INTO estudiantes (identificacion, tipo_documento, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, nombre, correo, telefono, num_registro, semestre, programa, tipo_programa, puntaje_global, nivel_global, comunicacion_escrita, comunicacion_escrita_nivel, razonamiento_cuantitativo, razonamiento_cuantitativo_nivel, lectura_critica, lectura_critica_nivel, competencias_ciudadanas, competencias_ciudadanas_nivel, ingles, ingles_nivel_mcer, formulacion_proyectos, formulacion_proyectos_nivel, pensamiento_cientifico, pensamiento_cientifico_nivel, diseno_software, diseno_software_nivel, aprobado_saber_pro, activo, fecha_examen) VALUES ('1030678936', 'CC', 'Jorge', NULL, 'Restrepo', NULL, 'Jorge Restrepo', 'jorge.restrepo@estudiante.universidad.edu.co', '3157000036', 'EK20183028123', 10, 'Ingeniería de Sistemas', 'Profesional', 96.0, 'Nivel 1', 0.0, 'Nivel 1', 117.0, 'Nivel 1', 122.0, 'Nivel 1', 105.0, 'Nivel 1', 137.0, 'A1', 157.0, 'Nivel 3', 96.0, 'Nivel 1', 131.0, 'Nivel 2', false, true, '2026-05-15');
